-- 1. TASK
SELECT NOW();
-- 2. TASK
SELECT YEAR(NOW()) AS Jahr, MONTH(NOW()) AS Monat;
-- 3. TASK
SELECT TIME(NOW());
-- 4. TASK
SELECT DAYNAME(NOW());
-- 5. TASK
SELECT MONTH(NOW());
-- 6. TASK
SELECT DAY('2020-03-18');
-- 7. TASK
USE shop;
-- 8. TASK
SELECT * FROM ORDERS WHERE MONTH(ODATE) = 4;

-- 9. TASK
SELECT COUNT(*) AS Anzahl_der_Käufe 
FROM ORDERS 
WHERE YEAR(ODATE) = 2022;
-- 10. TASK
SELECT ODATE, COUNT(*) AS Anzahl_der_Käufe 
FROM ORDERS 
GROUP BY ODATE 
ORDER BY Anzahl_der_Käufe;
-- 11. TASK
SELECT AVG(AMT) AS Durchschnittspreis 
FROM ORDERS 
WHERE MONTH(ODATE) = 4;